### PR TITLE
create kind cluster inside VM as bootstrap cluster

### PR DESCRIPTION
**Pull request by figo**
Signed-off-by: Hui Luo <luoh@vmware.com>

### CODE REVIEW

**Comment by akutz** [comment]
Hi @figo,

Thank you!!! FWIW, I’ve been testing with Kind 0.3.0. Is there any reason we can’t use that version?

**Comment by akutz** [comment]
Also, @andrewsykim has run into environmental issues with Kind/Docker on Ubuntu 16.04. The same issues did not occur on my CentOS dev box with his manifests. What OS is the box on which Kind is running?

**Comment by figo** [comment]
using kind 0.3.0 should be fine, nothing depends on specific kind version, just i am using that version right now.

also the VM is indeed ubuntu 16.0.4, what kind of environment issue there is?

**Comment by akutz** [comment]
We haven’t figured it out yet. He’s going to dig into it tomorrow. Can you try a single, manual test on your VM with my fork?

**Comment by akutz** [comment]
Know what, never mind. I’ll just try this and if it works, great. Thanks again hui!

**Review by akutz — APPROVED** [review]

**Pull request merged**
